### ISSUE TITLE
Rspec system test fails to compile 

### ISSUE THREAD

**Issue by seanpaulkelley** [shakacode/react_on_rails#1037]
when I run my system test, javacript does not appear to compile
rspec spec/system

The rails console shows:
====> React On Rails: Checking /home/me/projects/myproject/public/packs-test for outdated/missing bundles

fail

I posted this on stack overflow over 3 weeks ago with no response:
https://stackoverflow.com/questions/48567070/react-on-rails-system-test-compile-fails

Any ideas on making it work would be appreciated

**Comment by justin808** [comment]
This seems to be a bug in your project rather than an issue with React on Rails.

Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin

**Comment by seanpaulkelley** [comment]
it would be nice to know what failed.  just the word 'fail' is not helpful.
