### ISSUE TITLE
Tutorial: webpack-dev-server error with prerender: true

### ISSUE THREAD

**Issue by naartjie** [shakacode/react_on_rails#1192]
Hi, I just went through the [tutorial](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md).

When I turn on `prerender: true`, I get the following error when running `webpack-dev-server` with `foreman start -f Procfile.dev-server`:

```
ERROR in SERVER PRERENDERING
Encountered error: "TypeError: Cannot read property 'prototype' of undefined"
when prerendering HelloWorld with props: {"name":"Stranger"}
```

`foreman start -f Procfile.dev` works fine, and when I deploy to Heroku the server rendering is working there too. 

I tried both the default flow, which gave me `webpacker 3.5.5` and then the flow with the `webpacker 4.0.0.rc.7` installed from git, and I get the same error. Sorry if I missed something obvious in the tutorial.

Other versions:
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]`
`gem 2.7.6`
`bundler 1.17.1` (downgraded from `2.0.x` to work with Heroku?)
`rails 5.2.2`
`react_on_ruby 11.2.1`

**Comment by naartjie** [comment]
Thanks @justin808 

May I suggest making the tutorial single track, and taking out all the options. It might be more approachable to newcomers. As an example, maybe `foreman start -f Procfile.dev-server` should not be mentioned in the main tutorial? The same for `webpacker v4`, just to make it as clear as possible.

All the options and extra information can still exist, but listed after the end, so as to reward the person with some dopamine for completing the basic tutorial ;-)

**Comment by tahsin352** [comment]
@naartjie 
@justin808 
I have investigated the issue. SSR + webpack-dev-server. below is my findings:
if you run it you will see error:

No such file or directory @ rb_file_s_mtime - http://localhost:3035/packs/js/hello-world-bundle-d6b897068b8d31a768b8.js

the reason is:
webpack-dev-server runs in memory, If you want to see the files on disk during development you need to run the standard webpack. If you need to see from where webpack is serving the files without writing the content to disk, visit http://localhost:3035/webpack-dev-server on your local.

the webpack-dev-server is just a feature to enhance your speed of development. it's just there basically to refresh your browser. So even though it does some bundlings, that is solely for its own use and not for you(user). And that's why the build is not made available in your current working directory. So just see webpack-dev-server as for hot-reloading.

another issue is if you run SSR + HMR, you need to you redux to store state. otherwise it will give error. 

Thanks.

**Comment by naartjie** [comment]
Ok, I'm going to close this issue, as I'm not sure what else can be done here. Thanks!
