### ISSUE TITLE
npm install with --save installs node_modules in root, not in ./client

### ISSUE THREAD

**Issue by marcellosachs** [shakacode/react_on_rails#120]
Not sure if this is an issue with this library or with one of it's dependencies.

**Comment by alexfedoseev** [comment]
If you run `npm install --save some-module` in the root, `some-module` will be installed in root's `node_modules`. It's normal npm behaviour. So if you want to install some npm module — always run command in `client/` dir.

You can run `npm install` from the root only if you want to install all npm deps of the current project. See this line to understand what actually happens in this case: https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/templates/base/base/package.json#L11

You run `npm install` from the root -> since there are no deps in the root it installs nothing -> npm triggers postinstall script, which cd you to `client/` dir and installs all deps from the `client/` dir.

**Comment by marcellosachs** [comment]
Ok gotcha. Thanks for the explanation!
