### ISSUE TITLE
data-turbolinks-permanent do not unmount component

### ISSUE THREAD

**Issue by mariosar** [shakacode/react_on_rails#1223]
I am using Rails 5 with turbolinks and react_on_rails and would like for a particular component to persist across turbolinks page loads (state, props).

`<div id='cart-counter' data-turbolinks-permanent>`
`  <%= react_component("CartCounter", props: {key: val}) %>`
`</div>`

Right now the component is unmounted and then mounted again on each turbolinks page change. I would like for the component to be untouched on page change - sort of like a chat window that persists open when a user switches the page.

**Comment by justin808** [comment]
@mariosar did you solve this yet? 

Turbolinks works by replacing the body with each request, so it's doing what would be expected.

I'm not familiar with this sort of use case with Turbolinks. Many React on Rails apps are using react-router rather than turbolinks, so there is much more control over the client app.
