### ISSUE TITLE
Make use without Webpacker a supported case?

### ISSUE THREAD

**Issue by geoffharcourt** [shakacode/react_on_rails#1369]
Hello!

First off, this is an awesome project and has been extremely useful to us by providing a straightforward server-side rendering solution for use with our application.

Would you be open to a PR that removed the required of Webpacker? We went source-diving to enable use with our application without Webpacker and saw some comments indicating that the future of the library was to make Webpacker a hard dependency.

We were able to make things work without Webpacker by overriding `ReactOnRails::Utils.server_bundle_js_file_path` if there's any possibility to retain this capability, it would allow users of any asset bundling solution to leverage the really excellent SSR capabilities.

**Comment by justin808** [comment]
Hi @geoffharcourt! Thank you for the kind words! You made my day! I hope you consider trying out https://www.shakacode.com/react-on-rails-pro/. It's got some things your project might love! We are almost done with including bundle caching so that you don't have to constantly wait for the same bundles to get built over and over on many machines, such as CI, Review Apps, Staging, etc.

For sure, I'd be open to the PR as you describe! I made rails/webpacker a requirement to simplify things.

In your PR, please be sure to document how you'd use the gem without webpacker in terms of the view helpers.

Also, do note that you currently don't need to use the JS part of Webpacker to build your bundles.

**Comment by geoffharcourt** [comment]
This turned out to be more complicated than I had thought! We're looking into other ways we can generalize our changes to allow use of the SSR functionality outside of Webpacker, but this probably isn't the right change.
