### ISSUE TITLE
Remind users that server config file is required. 

### ISSUE THREAD

**Issue by jbhatab** [shakacode/react_on_rails#14]
Workaround temporarily in only client rendering desired:

create an empty file in Rails project `app/assets/javascripts/generated/server.js`.

**Comment by justin808** [comment]
Action Plan:

- [ ] If no generated/server.js exists, then do not include the file.
- [ ] Change the default of prerender to false, because it takes extra care to create a react component that can prerender. Make this configurable so the config file.
- [ ] Change the spec/dummy app to support the points above, and update the docs.
- [ ] Create a PR on the https://github.com/shakacode/react-webpack-rails-tutorial that is the simplest thing, which is just including the gem but no server rendering.
- [ ] Create a second PR (or just new branch) based on the last commit (if not merged to master) that shows the change to make this enabled for server rendering.

**Comment by justin808** [comment]
We're going to make this file optional, and configurable.

**Comment by justin808** [comment]
Fixed in #29
