### ISSUE TITLE
How to create Procfile.dev?

### ISSUE THREAD

**Issue by TangMonk** [shakacode/react_on_rails#1525]
./bin/dev warring:

```
Using foreman
ERROR:
Please ensure `Procfile.dev` exist in your project!
```

**Comment by TangMonk** [comment]
Ok, I got, there is a `Procfile.dev-static` exist. just rename it

But it shoule appears in document

**Comment by ahangarha** [comment]
If you have followed the documentation, after installed react_on_rails it creates this file for you. You don't need to create it manually. And the content of `Procfile.dev` is different from `Procfile.dev-static`.

Your issue is with `./bin/dev` which will be fixed in the coming release. Meanwhile, you can copy the content of the file [from master branch](https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/bin/dev).
