### ISSUE TITLE
Generator Error for application.scss

### ISSUE THREAD

**Issue by aaronvb** [shakacode/react_on_rails#189]
When I was creating tests for the generator errors, I noticed I could not get the application.scss exist? error to show up when skipping the creation of it in the test setup using ```application_css: false```

Here we check if ```application.scss``` exists:
https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/bootstrap_generator.rb#L56

However, it will always exist because of the previous method above it, so it's impossible to get the error:

https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/bootstrap_generator.rb#L23

Do you think the add error is necessary?

(cc: @robwise)

**Comment by justin808** [comment]
@aaronvb Please see if this is happening with v2. We're probably going to stop fixing bugs for v1.x

**Comment by robwise** [comment]
@aaronvb @justin808 I think this issue will still be happening in v2 as it's not related to what we've changed. Basically, we are checking for something that cannot ever happen, because originally we warned if the user was missing an application.scss but now we just make them one and we must have forgot to get rid of this. So I would say good catch Aaron, remove the error.
