### ISSUE TITLE
Leveraging React.rb

### ISSUE THREAD

**Issue by ylluminate** [shakacode/react_on_rails#271]
I would think for a true isomorphic experience we should be looking more closely to leveraging http://reactrb.org with this.

**Comment by justin808** [comment]
The goal of this project is React with tight integration of native JavaScript tooling, including Webpack and Babel. Trying to do the front-end setup in Ruby runs counter to the ability to stay at the cutting edge of JavaScript development.

**Comment by ylluminate** [comment]
I understand what you're saying, but I don't see that as true in our experience so far with wrappers we've been involved with.

**Comment by justin808** [comment]
@ylluminate How would you see ReactRb used with ReactOnRails?

**Comment by fkchang** [comment]
@justin808 I will probably attempt the integration that I think @ylluminate is referring to.  Presently react.rb is integrated with react-rails to provide Rails integration, and I believe @ylluminate's notion is that we would just substitute react_on_rails for the equivalent functionality.

I really agree with your idea of being a "1st class Javascript citizen" and believe that for Opal to succeed, it needs to do the same thing that JRuby does -- i.e. allow easy integration w/the the entire, vibrant JVM ecosystem., on top of being able to run Ruby on gems.  That being said, Opal can pretty much do so via webpack in the same way you've done it for react_on_rails..  I've already got a react.rb/react-rails/webpack/jruby/vertx/jubilee app running that uses npm modules as part of the client side of app. Where react.rb shines is that I get a better/more powerful DSL, and true isomorphic code where I can I can share domain logic both w/react.rb and Rails, as well of having some nice Rails to Opal integrations that opal-rails supports.  This sort of situation is much closer to the JS vision of the same, IMO.

It's my opinion that, react.rb's current implementation is overly coupled to react-rails, so extricating might not be particularly easy at first, but I have desire to so do so that we can provide isomorphic Ruby code w/any Rack backend.  Offhand though, if I can use webpack w/react-rails, which I am, I'm not sure what additional benefits one would get by switching react-rails for react_on_rails.  I suppose the primary one is to outsource leading edge webpack practices to the react_on_rails team, which is always a good thing. 

Great job on react_on_rails, btw.

**Comment by justin808** [comment]
Thanks @fkchang. If there's anything I can you with, please let me know!

At the same time, while I love **RUBY**, I sure love **ES6/ES7** as well!
