### ISSUE TITLE
Voting on Future Features and Supporting React on Rails

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#289]
There's no obvious mechanism to collect votes on future features.

I'm opening up this "issue" as a placeholder for general comments about what people would like to see next.

[ShakaCode](http://www.shakacode.com), my company, has paid for many hours of developer's time to support the project.

We super, super appreciate community support through:

1. Reporting issues and using React on Rails.
2. Helping others use React on Rails.
3. Submitting PR's for any features (best to discuss first with me if it's a lot of work).
4. Hiring us for a starter pack of consulting to get up to speed on this. See [Coaching for React on Rails](http://www.shakacode.com/work/).
5. Funding us to do a feature that matters to you, and your team doesn't have the time to do the PR.

**Comment by kayakyakr** [comment]
Coming at this as someone completely new to React, evaluating JS libraries, so fresh eyes:

1. Install process should be streamlined. It's OK for new projects, but you modify too many existing files for established projects looking to integrate React on Rails. Route, application.js & css, adding a controller, tasks, etc. I know you're trying to be opinionated, but I'd rather see a "way" than a bunch of stuff that I'll wind up deleting. Plus you generate Profile.dev-hot which is identical to dev but with a todo.
2. Continuing the theme I'd prefer to see a blank project with directories set up than a hello world
3. Take a look at and shamelessly steal from https://github.com/thoughtbot/ember-cli-rails. I like how their stuff runs embedded in `rails s` rather than having its own startup process via foreman. Their asset process is also nice, but it does not use rails assets. Worth evaluating if it would be appropriate to do something similar
4. your tasks could probably live inside the gem?

**Comment by justin808** [comment]
@kayakyakr Great feedback! @jbhatab is working on simplifying the generator setup. @seoyoochan is working with me on some features.

@kayakyakr Let me know if you'd like to join our slack room. If you can help us with some of your great ideas, that would be awesome!!!

**Comment by kayakyakr** [comment]
Just gave a talk on a migration path to React for the team I'm working with, including an intermediary hybrid step. I actually wound up going with Browserify + Babelify to start because it's a less intrusive setup, but if you can emulate a lot of what ember-cli-rails does (namely running their watch, lint, and compile process in server, the way they serve assets, and serving source maps by default), then I'd switch back in a heartbeat.

I'd be happy to sit in Slack, but I can't promise to provide anything more than commentary. The timelines don't allow for much OS work, unfortunately.

**Comment by justin808** [comment]
@kayakyakr Send me an email or other contact info!

**Comment by justin808** [comment]
@kayakyakr Latest generator is much less intrusive for v6. You can ask @jbhatab as he worked on it.

**Comment by kayakyakr** [comment]
I saw that, much improved. The biggest remaining weakness of this project is how it interacts with sprockets. Ideally you'd be using /tmp/cache in a way similar to ember-cli or browserify.
