### ISSUE TITLE
Surface js compile errors

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#316]
Hi,
when I have an issue with the JS code and it doesn't compile, I have to shutdown the server and run it again, to get a sensible error message.

I tried to run the `npm run build:dev:client` in a window by itself in hope that it would produce output every time there is a compile error, but that doesn't happen (only the first time).

Is there a way to have the compile error surfaced to the developer without restarting the server / or the build command?

**Comment by justin808** [comment]
@hakunin That doesn't really make sense, in that Rails is a Ruby program. If you have a JS error, that will affect Webpack.

I think your issue is with running the `webpack -w` via foreman. You can run the commands in your Procfile in different tabs rather than using foreman. If you're going to do this lots, google "consular" or "tumuxinator". These programs will quickly open up several terminal tabs for you with different processes. I used to do this all the time. Now, foreman is good enough for me. Also, foreman does not always flush the buffers, so console log messages can get delayed.

**Comment by hakunin** [comment]
Thanks, it turns out I wasn't running the full command from foreman, just the part of it and sometimes it would not seem to give errors when I intentionally put one there.
