### ISSUE TITLE
I have to restart the compile script all the time

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#333]
1) When there is a parse error, the compile script has to be restarted, or the app somehow doesn't work.
2) Sometimes the same occurs, even without parse error

Short video showing the issue:
http://screencast.com/t/xXtwtYGuJyQ

**Comment by justin808** [comment]
@hakunin I think this is just the general issue rather than with React on Rails.

Can you reproduce this issue with https://github.com/shakacode/react-webpack-rails-tutorial/ or the /spec/dummy app?

If you can't, I think there's a problem with your setup.

Note, there's been tons of updates to npm packages, etc. since you may have started your app. First update to the versions used in either the tutorial or spec/dummy.

**Comment by hakunin** [comment]
You're right. Updated everything and the problem went away. Thanks!
