### ISSUE TITLE
`data-dom-id` collision with (fragment) caching

### ISSUE THREAD

**Issue by michaelbaudino** [shakacode/react_on_rails#437]
We encountered a problem where `data-dom-id` of components on the same page are not unique.

This is particularly obvious when components are stored in cache fragments and can be ordered differently depending on parameters. For exemple, think about search results where each result is a cache fragment containing a component rendered using `react_component` (the fragment will contain the `data-dom-id` auto-incremented based on the rank this result had in the page **when rendered the first time**).

For the record, if some people have the same problem, the workaround we found is to explicitely define `data-dom-id` using the `id` parameter of the `react_component` method [as documented here](https://github.com/shakacode/react_on_rails#react_component).

The point of this PR is that the default `data-dom-id` should actually not be auto-incremented based on the rank of the component in the page, but rather by an UUID or (even better, but not sure if possible) by a MD5/SHA hash of its content.

PS: I saw a few existing issues related to fragment caching, but it was more about cache invalidation, not that kind of collision.

**Comment by justin808** [comment]
@michaelbaudino Thanks for reporting this. We should get a fix out ASAP. If you have any other feedback, please let me know. A PR would definitely be appreciated.

**Comment by justin808** [comment]
@michaelbaudino We probably don't actually need the auto-generated DOM ID for anything other than integration tests (what do we need this for?):

Let's have a config setting:

`dom_id_generator`: Values:

* false: (default) which means none
* UUID (don't really know about MD5)
* Allow the value to be a proc, so you can have a custom function, and we provide an example of this that gives the old behavior, which could be used just for tests, so that there's a super simple upgrade path for those apps depending on this.

@jbhatab @thewoolleyman @alexfedoseev @robwise Any comments?

Feedback is welcome.

We'll need a major version bump for this.

In the very short term, we need a doc PR to address this. We should have a doc file for Fragment Caching tips. (any volunteers?: call it `/docs/additional-reading/fragment-caching.md`)

@michaelbaudino Please share your tips on how you set up your cache key with react_on_rails. I'd like to consider eventually making a helper for this.

**Comment by michaelbaudino** [comment]
You mean, kinda like #438 ? :smile:

**Comment by justin808** [comment]
Yes, for anybody reading this. See #438. Big thanks to @michaelbaudino for fixing this!

**Comment by justin808** [comment]
I want to get this one merged. The only thing holding me back is getting consensus on doing a major version bump. I think it's prudent to do a major version bump so somebody doing updates will look at the CHANGELOG.md.

@michaelbaudino Agree?

**Comment by michaelbaudino** [comment]
Sure, great ! Thanks a lot :sparkles:
