### ISSUE TITLE
Wrapper component in SPAN

### ISSUE THREAD

**Issue by BrunoQuaresma** [shakacode/react_on_rails#480]
Is possible i wrapper my component in span instead div?

**Comment by justin808** [comment]
@BrunoQuaresma Why would you do that? Check the react docs if that is possible. I don't think it is. I'd recommend just configuring the styling of the div to act like a span. You can do that.

**Comment by BrunoQuaresma** [comment]
In react-rails gem has the option 
`html_options: { tag: 'some-tag' }` 
but this option render something like:
`<div tag="span" id="ButtonApp-react-component-0">`
when i expected
`<span id="ButtonApp-react-component-0">`
So, the solution that i found was change the style inline:
```
<%= react_component("ButtonApp", props: {
            id:"referral-action-button",
            label: publisher_decorator.action_button_description,
            btnType:"primary",
            type:"button",
            size: "sm",
            isDisabled: false,
            style: "btn-raised",
            secondaryStyle:"js-next-phase",
          }, html_options: { style: "display:inline-block" }) %>
```

**Comment by justin808** [comment]
Hi @BrunoQuaresma, I updated the README.md. 

![2016-07-20_19-43-07](https://cloud.githubusercontent.com/assets/1118459/17012304/3324ac86-4eb2-11e6-8478-56f4e65579c2.png)

**Comment by BrunoQuaresma** [comment]
Thanks @justin808 !

**Comment by risinglf** [comment]
Hi all,
thanks guys for this gem!

@BrunoQuaresma @justin808 I think it would be great to have the ability to choose which element use as wrapper, as react-rails does.

I used the `html_options: { style: "display: inline-block"} ` but it cannot always work.

Eg: I want to have a react component as an item in a bootstrap navbar-nav, the css rule is:
`.navbar-nav > li`

With react-rails I always used the `tag: 'li'` option, with react_on_rails this is not possible and having a div that wraps the component breaks the markup.

What do you think?

**Comment by justin808** [comment]
@risinglf Please open a new issue if you feel strongly about this. Please include info about why this is worth the extra complexity.

**Comment by argasek** [comment]
@justin808 Hi, I hit the same issue as @risinglf and I got quite a strong case why such feature is necessary. I render my component enclosed in `<p>...</p>` tag. As react_on_rails renders in `<div>`, it leads to semantically incorrect HTML nesting - `<div>` is not allowed in `<p>` which, in turn, makes the React component rendered as `<div>` *outside* the `<p>` tag:
![Incorrect nesting](https://preview.ibb.co/cTuste/Screen_Shot_2018_10_01_at_13_03_30.png)
I'm forced to change `<p>` to `<div>` in order to have a correct nesting:
![Correct nesting](https://preview.ibb.co/mwO7Rz/Screen_Shot_2018_10_01_at_13_04_21.png). Such change makes the HTML code less accessible for screen readers and bots. There are really good reasons why HTML5 have various tags (p, div, span, strong) to denote different _functions_ of web page elements, not just the way they are rendered. Broken markup also makes SEO difficult.

**Comment by justin808** [comment]
@argasek I can pair with you on PR to add this. Should be easy to allow an option for that.

If you don't have time for a PR, I can do this for you in the context of [our services work](https://www.shakacode.com/work/shakacode-pro-support.pdf).

**Comment by tahsin352** [comment]
@justin808 Please review my PR: https://github.com/shakacode/react_on_rails/pull/1208 regarding this. Thanks
