### ISSUE TITLE
Update readme request

### ISSUE THREAD

**Issue by chiraggshah** [shakacode/react_on_rails#551]
While using the gem, I found 2 things which are not included in the readme. (I might be wrong, since the readme is quite exhaustive. If they are already included, please point it out and close this issue) :

- While exporting a new component, it has to included in `./client/webpack.config.js`

- When a new JSX file is created, it requires a server restart.

If its not included in the readme, I would be happy to submit a PR. Thanks.

**Comment by justin808** [comment]
@chiraggshah That's webpack bundles rather than React on Rails. You don't have to start the rails server. You have to restart the webpack watch process process when you change the config file.

> While exporting a new component, it has to included in ./client/webpack.config.js
Absolutely not, unless you make a new bundle.

> When a new JSX file is created, it requires a server restart.
You're forgetting to run either the watch option for webpack to automatically build your files or using the hot reloading option.
