### ISSUE TITLE
react_on_rails in multiple gems

### ISSUE THREAD

**Issue by kschuste** [shakacode/react_on_rails#654]
I have made two sample gems to help show what I am trying to get around. Can check out both in the same directory as base references dependent locally. With base, I am trying to render the react component inside dependent as well. However, it only finds the component registered in base. Is there a way I can get both registered and keep them in separate gems?

https://github.com/kschuste/react_on_rails_base
https://github.com/kschuste/react_on_rails_dependent

If start of the server in base and navigate to localhost:3000/hello_universe
you will get the following error:

Exception in rendering!

Message: Could not find component registered with name HelloWorld. Registered component names include [ HelloUniverse ]. Maybe you forgot to register the component?

Error: Could not find component registered with name HelloWorld. Registered component names include [ HelloUniverse ]. Maybe you forgot to register the component?
at Object.get (eval at (unknown source), :63:11)
at Object.getComponent (eval at (unknown source), :223:40)
at createReactElement (eval at (unknown source), :46:45)
at serverRenderReactComponent (eval at (unknown source), :45:71)
at Object.serverRenderReactComponent (eval at (unknown source), :232:53)
at :5:23
at :12:3

**Comment by justin808** [comment]
@kschuste I'd recommend looking into the creation of the deployment bundle names. My guess is that you're using the same name for both, and thus overwriting one or the other.

React on Rails is designed for one config, and that will have one server rendering file. You will want to configure your webpack build process to build everything into one server file.

**Comment by kschuste** [comment]
I purposefully made the bundle names separate.  The base gem has it defined as 'base-bundle.js' and the dependency gem has it defined as 'dependency-bundle.js'.  Each gem does have it's own react_on_rails.rb config since each can be run separately.

**Comment by toastercup** [comment]
@justin808 I'm running into the same issue, but I'm following a different architecture than @kschuste. Instead of multiple Gems that have their own `react_on_rails` instances and `bundles`, I'm packaging my React components as regular node packages. Ideally, I'd like these plugin components to register themselves with `ReactOnRails`, because our platform doesn't know what plugins our users are going to load ahead of time. However, depending on the order, one will overwrite the other - either the base app will override the registration of the plugin components, or the plugin components will override the base app's registered components. I've tried every which way of requiring, importing, etc the plugin components, to no avail. If I import and mount the plugin component from the main app, it works just fine.

Should I be packaging these plugin components differently? Is having the plugin components mount themselves via `ReactOnRails.register` a poor idea in general?

Could @kschuste's issue and mine be related?

**Comment by justin808** [comment]
@kschuste and @toastercup I really don't know. I'd be looking to get consensus from you both on the best approach and take either doc or code PRs into the React on Rails codebase.

**Comment by toastercup** [comment]
@kschuste Adding `react-on-rails` to the `entry` points array in `webpack.config.js` did the trick. This ensures `ReactOnRails` is loaded and made available to all modules in `entry` after its declaration. Previously, `import`ing `ReactOnRails` would re-initialize the object and wipe away any previously registered components.

For example:
```jsx
const config = {
  entry: [
    'es5-shim/es5-shim',
    'es5-shim/es5-sham',
    'babel-polyfill',
    'react-on-rails',
    ...pluginPackages,
    './app/bundles/HelloWorld/startup/registration.jsx'
  ]
}
```

If this goes against best practices, let me know - I'm still getting my feet wet with Webpack!

@justin808 is this something you'd like to see documented or changed in the platform? I can contribute a PR if you think it'd be helpful.

**Comment by justin808** [comment]
Normally, we put shared libraries in one bundle called "vendor". 

If you have multiple bundles and are not removing duplicates (via Webpacks tooing for that), then you will have problems with other libraries as well.
