### ISSUE TITLE
Generator raises error when application.js is not found

### ISSUE THREAD

**Issue by rupurt** [shakacode/react_on_rails#78]
We currently have our application split up into multiple smaller applications so don't use the main `application.js` file. It would nice if the generator allowed you to specify the name of the manifest file e.g.

```bash
rails generate react_on_rails:install -m my_cool_app
```

**Comment by justin808** [comment]
@rupurt As a workaround, just create an empty file right now.

If you could submit a PR for your enhancement, we'd take it!

**Comment by rupurt** [comment]
@justin808 that's what I did :smile: 

I'll see if I have some time to take a stab at it over the weekend.

**Comment by robwise** [comment]
@rupurt That would be awesome! Definitely take a look at the `lib/generators/react_on_rails/base_generator.rb` file, as I believe this may be the right place for this logic. We could also try putting this logic inside of the `config/initializers/react_on_rails.rb` initializer, although I'm not sure if that work and/or maybe that's not a solution for your specific scenario.

**Comment by yorzi** [comment]
Generator raises error when `application.css.scss` is not found as well (in our case we use application.scss), I think it's a similar issue. It might be good to be able to config these files in initializer.

**Comment by robwise** [comment]
@yorzi I would say this issue is an enhancement, whereas yours is closer to a bug. I have therefore made a separate issue: https://github.com/shakacode/react_on_rails/issues/86

**Comment by yorzi** [comment]
@robwise :+1: I can look into that today.

**Comment by justin808** [comment]
@yorzi Would be awesome if you can submit a PR to fix the missing files!

**Comment by justin808** [comment]
@robwise Can we close this one?

**Comment by robwise** [comment]
@justin808 negative, I fixed a different issue that was with the application.scss, not js. This issue will still occur. I can come up with a fix if you want. 

1) We can allow passing an argument to specify a different file than application.js
2) We can simply create an application.js file if it is missing

The latter solution would not actually really fix @rupurt's problem, though, but it would at least let the generator run through completion by default instead of essentially forcing him to figure out that he needs to make his own application.js file, run the generator, and then move the code manually to where he wants it.

**Comment by justin808** [comment]
@robwise I vote for 2) with a warning as the user will see the diff and can take appropriate action.
