### ISSUE TITLE
Psych::DisallowedClass during some locale files convertion to js

### ISSUE THREAD

**Issue by dsawa** [shakacode/react_on_rails#798]
Hey,

I have recently updated React on Rails to the latest (6.9.3) and updated webpack to v2 (along with all configurations). However one thing changed that breaks my current project.

I get 
```
Psych::DisallowedClass: Tried to load unspecified class: Symbol
```
every time I for example run rake commands (impossible to run migrations).

During investigation I managed to find a simple solution. Problem occurs in [LocaleToJs](https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/locales_to_js.rb#L82).

If I change `YAML.safe_load` to just `YAML.load` it works. I could make a new PR with this small change, but I see that it was changed for some reason in PR that updated whole React on Rails to support webpack 2. What's the reason? 

It can be pain in the ass when relying on different locale files from different gems that you not necesarrly can control. In my example, origins of the problem are from spree_i18n gem (FR translations).

Should I make PR with change to `YAML.load` ?

**Comment by justin808** [comment]
@dsawa here's a discussion of the issue: https://github.com/ruby/psych/issues/119

I need some more details on why this fails. I'm guessing that there's something odd about your translation files using symbols for values rather than strings.

It's 100% clear that YAML.safe_load was added so that if don't want arbitrary objects, then so be it.

Why would you have a symbol?

CC: @JasonYCHuang

**Comment by justin808** [comment]
@dsawa is this still an issue?

**Comment by ilya4544** [comment]
Same issue here

**Comment by dsawa** [comment]
@justin808 Yes it is. Like @ilya4544 said, and me before, it's not me that I have symbol or something in translations. Those locales come from other gem.

I'll try ilya4544 workaround later.

**Comment by justin808** [comment]
I'm open to a PR or reopening this discussion if needed.

**Comment by dimasjt** [comment]
I got the same issue, it's because the translation have symbol value, I use `i18n-rails` https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/zh-CN.yml#L59

**Comment by markopavlovic** [comment]
same issue here, sometimes you use symbols for date definitions

**Comment by AntonAL** [comment]
I had the same issue, found recent changes in my .yml file, that had used definitions like this:
```
formtastic:
    :yes: 'Да'
```
Changed `:yes` to `yes` like this,

```
formtastic:
    yes: 'Да'
```

and issues was disappeared.

**Comment by dzirtusss** [comment]
@justin808 overall, I agree that `YAML.safe_load` is the proper way, but... sometimes it is not under the user direct control and is burried in third-parties gems (e.g. `formtastic`). And because it is burried in gems, there is no good stacktrace either to debug the problem - just `Psych` crashed on `Symbol` and that's it.

I guess it can be improved in 2 ways:
1. add a `rescue` with better error/message which will print what locale file had issues and crashed. Thus it can be debugged quickly.
2. add a "hacky" option that could be passed to `YAML.safe_load(file, **yaml_locale_load_options)`. Thus it can be configured `yaml_locale_load_options: { permitted_classes: [Symbol] }`

I mean I've seen people installing problematic gems in docker, and then patching source code locales with linux tools as a step to deal with this. Because gems are not under their control.
