### ISSUE TITLE
[Rails 3] Create Rails 3 Unit tests

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#814]
@ynote commented on #812:

> I'm not really sure that mocking the version is the better way to do.
> Could it be a good idea to configure Travis to lauch the tests with differents Rails version? I'm just raising the question, I know this imply to extend the tests duration and to change the Travis configuration.

Yes, but it would take:

1. /spec/dummy-rails3 (like spec/dummy, but with Rails 3)
2. pass env value on travis runs for different ruby versions and ONLY run rails 3 tests (spec/dummy-rails3) and unit tests) for the old ruby version. Don't run /spec/dummy and the generator tests.

**Comment by morozovm** [comment]
Hi @justin808 I need some guidance. I was able to make "gem" tests to run on rails 3.2 (without generators tests and webpack related tests) #914 
What exactly do you like to see in /spec/dummy-rails3 ?
Maintaining two very similar dummies seems cumbersome, I explored the possibility of running /spec/dummy on older versions and was able to run on 4.2 but not lower since /spec/dummy depends on webpacker_lite which requires rails 4.2

**Comment by justin808** [comment]
@morozovm: I reviewed and it looks great.
