### ISSUE TITLE
Documentation missing/unclear on RailsContext?

### ISSUE THREAD

**Issue by ceres629** [shakacode/react_on_rails#879]
I can't seem to find any solid information on how railsContext works and how to access the railsContext from within a component.

I have some server side size variables such as ENV variables that I want react components to be able to access. Normally I'd just pass them as props however reading the documentation it says:

> While you could manually pass the railsContext information in as "props", the rails_context is a convenience because it's passed consistently to all invocations of generator functions.

I thought this mean I could set up a rails_context to contain the information i need, and then whenever I use react_component it will have a railsContext parameter automatically added that I can use to access the railsContext from within the component.

the definition of these components are

export default (_props, _railsContext) => {
 }

which seems to suggest some how there is a railsContext being passed in. But although my _props contain values as expected, _railsContext is always null and I can't find any documentation that explains how you pass this value in. Searched online for a few hours to no avail. In the end I just decided to pass rails_context in as a prop, which works, but I'm still confused as to what this railsContext is for or if it is broken or just lacking documentation.

**Comment by MiguelSavignano** [comment]
Hi, @ceres629 
I use the rails context a lot in my app. To sure you load the context appropriately
 see https://facebook.github.io/react/docs/context.html.

The child component need define contextTypes
```javscript
Button.contextTypes = {
  color: PropTypes.string
};
```
I miss a good documentation for react on rails context, I implemented a custom context provider and pass the context in as a prop.

**Comment by justin808** [comment]
I created an example:

https://github.com/shakacode/v8-demo/pull/2

I'm working on making the documentation more clear.

**Comment by justin808** [comment]
See #886, @MiguelSavignano and @ceres629. Please review.

**Comment by MiguelSavignano** [comment]
The example with generator function it's great but Why if my component it's a React Class the context don't appear.
```javascript
import React from 'react';
class RailsContextExample extends React.Component {
  render(){
    return (
      <div>
        <p>props are: {JSON.stringify(this.props)}</p>
        <p>railsContext is:
          {JSON.stringify({ ...this.context, serverSide: false})}}
        </p>
      </div>
    )
  }
}
export default RailsContextExample;
```

And other thing i try to add new context key like params_action or current_user_id I try to override rails_context helper method but this method it's private and I can't do this.

**Comment by justin808** [comment]
@MiguelSavignano There's no reason that the railsContext would ever get passed to your React component unless the value is explicitly put into the props used for rendering. If you create a react component, rather than a generator function, for use by React on Rails, then you get whatever props are passed in from the view helper, which **does not include the Rails Context**. It's trivial to wrap your component in a "generator function" to return a new component that takes both:

```js
import React from 'react';
import AppComponent from './AppComponent'; 
const AppComponentWithRailsContext = (props, railsContext) => (
  <AppComponent {...{...props, railsContext}}/>
)
export default AppComponentWithRailsContext;
```

Consider this line in depth:

```js
  <AppComponent {...{ ...props, railsContext }}/>
```

The outer `{...` is for the [JSX spread operator for attributes](https://facebook.github.io/react/docs/jsx-in-depth.html#spread-attributes) and the innner `{...` is for the [Spread in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#Spread_in_object_literals).


@MiguelSavignano Should this go in the docs?

**Comment by justin808** [comment]
@ceres629 @MiguelSavignano Please see my updates to #886 and review.

**Comment by justin808** [comment]
@MiguelSavignano and @ceres629, while I merged, I'd still like to get your feedback.

**Comment by MiguelSavignano** [comment]
@justin808 Thanks for update the docs and include both examples.
